### ISSUE TITLE
Requisição de permissão de escrita no repositório

### ISSUE THREAD

**Issue by ghost** [letsdelfino/banco_SBD#2]
Sem aviso prévio, minhas permissões de escrita nesse repositório foram revogadas. Peço esclarecimentos quanto a essa decisão.
Sigo o desenvolvimento em um fork: https://github.com/expert975/banco_SBD/

**Comment by GDV1** [comment]
Sentimos muito, mas, sem aviso prévio, nosso repositório recebeu commits que alteraram drasticamente o modelo proposto e escolhido pelo grupo. Siga o desenvolvimento no fork e, na próxima aula, conversaremos melhor.
